import java.awt.Point;
import java.util.*;

/**
 * States to be used with A* in Graph, states calculate  their heuristic and
 * maintain a list of the inventory at that time, if the path uses a stepping stone
 * and the direction the player moved to reach it
 * @author Saffat Shams Akanda, Richard Luong
 * @see Graph#astar(Behaviour, Direction)
 */
public class State implements Comparable<State>{
	private State prevState;
	private Direction currDirection;
	private Point pos;
	private int fCost;
	private Point goalNode;
	private int hCost;
	private ArrayList<Tile> inventory;
	private boolean usesStone;
	
	private static final int impassableCost = Integer.MAX_VALUE - 0xffffff;
	
	/**
	 * Constructor for a State
	 * @param ps				Previous State / Null if first state
	 * @param d					Direction agent moved to get to this state
	 * @param p					Location of this state
	 * @param b					Behavior currently being used
	 * @param map				A reference back to the map
	 * @param inventory			A copy of the player's inventory
	 * @param goal				Location of goal node
	 * @param usesStone			If the stepping stone has been used
	 */
	public State(State ps, Direction d, Point p, Behaviour b, Graph map, ArrayList<Tile> inventory, Point goal, boolean usesStone) {
		this.prevState = ps;
		this.currDirection = d;
		this.pos = p;	
		this.inventory = inventory;
		this.usesStone = usesStone;
		
		calculateHeuristic(b, map, inventory, goal);
	}
	
	/**
	 * Calculates the heuristic and sets up the FCost of the state
	 * @param b				The behavior to calculate the heuristic
	 * @param map			The map
	 * @param inventory		Current player inventory
	 * @param goal			Location of the goal node
	 */
	public void calculateHeuristic(Behaviour b, Graph map, ArrayList<Tile> inventory, Point goal) {
		this.hCost = b.returnHeuristic(goal, pos);
		Tile currTile = map.getTileAt(pos.x, pos.y);
		int gCost = 0;
		
		goalNode = goal;
		
		// Paths that require an item require 2 moves to travel
		// If the item is not in possession path is impassable
		// Unexplored tiles represent uncertainty and should be avoided if possible
		// All other paths cost 1
		switch (currTile) {
		case Wall:
			gCost = impassableCost; break;
		case Tree:
			gCost = (inventory.contains(Tile.Axe)) ? 2 : impassableCost; break;
		case Door:
			gCost = (inventory.contains(Tile.Key)) ? 2 : impassableCost; break;
		case Water:
			gCost = (inventory.contains(Tile.StepStone)) ? 2 : impassableCost;
			usesStone = true;
			break;
		case Unexplored:
			gCost = 3; break;
		default:
			gCost = 1; break;
		}	
		
		this.fCost = (prevState == null) ? gCost + hCost : gCost + hCost + prevState.getGCost();
	}
	
	/**
	 * Recursively builds a list of moves to get to the goal
	 * @return		Queue of moves to reach the goal from the starting node
	 * @see Move
	 */
	public Queue<Move> getPath() {
		Queue<Move> qm;
		if (prevState == null) {
			qm = new LinkedList<Move>();
		} else {
			qm = prevState.getPath();
		}
		Move m = new Move();
		m.d = currDirection;
		qm.add(m);
		return qm;
	}
	
	/**
	 * Get the direction the player moved to reach this state
	 * @return		Direction player is facing in this state
	 */
	public Direction getDirection() {
		return this.currDirection;
	}
	
	/**
	 * Prints out the goal node then the path to reach this node
	 */
	public void printPath() {
		if (prevState != null) {
			prevState.printPath();
			System.out.print(" -> " + this.pos.toString());
		}
		else {
			System.out.println(goalNode.toString());
			System.out.print(this.pos.toString());
		}
	}
	
	/**
	 * Returns the g cost of the node, can only be accessed by State classes
	 * @return		G Cost of node
	 */
	protected int getGCost() {
		return this.fCost - this.hCost;
	}
	
	
	/**
	 * Getter for the function cost of a state
	 * @return		Integer function cost of state
	 */
	public int getFCost() {
		return fCost;
	}
	
	/**
	 * Gets a Point object representing the current position in the state
	 * @return		Point representing the current position
	 */
	public Point getPos() {
		return pos;
	}
	
	/**
	 * Returns if a stone has been used in the path to the state
	 * @return		If a stone has been used
	 */
	public boolean getStoneUsage() {
		return usesStone;
	}
	
	/**
	 * Get the player inventory at this state
	 * @return	Player inventory at this state
	 */
	public ArrayList<Tile> getInv() {
		return inventory;
	}

	/**
	 * Auto-generated by Eclipse
	 * Two states are equal if their positions are the same
	 */
	@Override
	public boolean equals(Object o) {
		if (o.getClass() == this.getClass()) {
			State otherState = (State) o;
			if (otherState.getPos().x == this.pos.x && otherState.getPos().y == this.pos.y) return true;
		}
		return false;
	}
	
	/**
	 * Compares two states using their F costs
	 */
	@Override
	public int compareTo(State o) {
		if (o == this) return 0;
		else if (o.getFCost() < getFCost()) return 1;
		else return -1;
	}
}
